default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: prototyper_development

test:
  <<: *default
  database: prototyper_test

production:
  <<: *default
  database: prototyper
