default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: containerdb_development

test:
  <<: *default
  database: containerdb_test

production:
  <<: *default
  database: containerdb
